### PR TITLE
Fix for WFLY-10614, modified and added tests to CLI

### PR DESCRIPTION
**Pull request by jfdenise**
- Added tests for completion (referenced-domain and mechanism are alternatives)
- Check that OOTB Security domain is set when nothing is provided.
- Test for new option --referenced-security-domain.

### CODE REVIEW

**Comment by mchoma** [comment]
@jfdenise  Seems PR is missing ElytronUtil change

@darranl wildfly security-incubator does not have CI integrated?

**Comment by jfdenise** [comment]
@mchoma , this test requires an upgrade to the wildfly-core that contains the CLI changes to build an run.

**Comment by mchoma** [comment]
@jfdenise Right, after wildfly core upgrade to 6.0.0.Alpha3-SNAPSHOT test pass. Thank you

**Comment by darranl** [comment]
@mchoma no we have no automated CI on any repositories where we have changes spanning multiple projects so we are into the territory of kicking off manual runs.

**Comment by darranl** [comment]
I am closing this PR as it has now been incorporated in the main PR submitted upstream.

**Pull request closed without merging**
