### PR TITLE
[WFLY-5745] Update RunAsPrincipalInterceptor to make use of the new SecurityIdentity.createRunAsAnonymous() method

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.jboss.org/browse/WFLY-5745

Depends on https://github.com/wildfly-security-incubator/wildfly-core/pull/13

### CODE REVIEW

**Comment by darranl** [comment]
I will go ahead and merge but for now I am stopping the updates to the repositories that switch to SNAPSHOT version - for things like Elytron I am happy to tag more regularly if we have a need and for the inter WildFly builds we can override the versions using system properties.

Also the new continuous integration builds completely override all versions with system properties so SNAPSHOTs work well there now without needing to tweak the poms.

**Comment by darranl** [comment]
@fjuma not sure why GitHub did not close this - can you please check if I missed anything on the merge?

**Comment by fjuma** [comment]
@darranl Looks like this wasn't merged in the elytron_integration branch. It was merged in the remoting5_integration branch though. This PR is a follow-up fix for the WFLY-5745 changes upstream.

**Comment by darranl** [comment]
Ah, I see - do you think we need to get this into WildFly quickly or can it wait until we merge the remotin5_integration branch which TBH is not far away?

**Comment by fjuma** [comment]
This can wait until we merge the remoting5_integration branch.

**Comment by dmlloyd** [comment]
This is another case where we are relying on a special string "anonymous" to represent non-identity.  I think we need to decide whether we globally recognize "anonymous" as a special principal, or whether we have a separate construct to represent run-as anonymous.  Another option is to use the empty string instead.

**Comment by fjuma** [comment]
The EJB subsystem currently uses the string "anonymous" when no run-as-principal-name has been provided (see https://github.com/wildfly/wildfly/blob/6b61a6003f704221f66dcd9f418bcb7af88fb9ab/ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/RunAsMergingProcessor.java#L48). We could change that to the empty string instead.

**Comment by dmlloyd** [comment]
Hmm making it a compatibility consideration makes it less straightforward.  The first priority has to be to retain the current behavior, but we should have an option to disable special treatment of "anonymous" and maybe we can also support "" as an indicator for anonymous authentication.

**Comment by dmlloyd** [comment]
Note that such an option can be added in the future!

**Comment by fjuma** [comment]
+1

**Comment by darranl** [comment]
@fjuma As this went into remoting5_integration can it be closed?

**Comment by fjuma** [comment]
@darranl Yes, closing this one now.

**Pull request closed without merging**
