### PR TITLE
Remoting5 integration

### PR DESCRIPTION
**Pull request by tadamski**
Merged my ejb3 subsystem work into remoting5_integration branch. Have to update wildfly-naming-client for the smoke tests to work.

### CODE REVIEW

**Comment by fjuma** [comment]
Discussed some compilation issues with @tadamski and found that building this depends on the following PRs:

https://github.com/wildfly/wildfly-transaction-client/pull/1
https://github.com/jbossas/jboss-ejb-client/pull/155

**Comment by tadamski** [comment]
After updating jboss-ejb-client to the HEAD new smoke test errors appeared:
DDBasedEJBTestCase#testDDOverrideOfSLSB
EarDeploymentEjbJndiBindingTestCase#testRemoteBindingsOnSFSB
StandaloneModuleEjbJndiBindingTestCase#testRemoteBindingsOnSFSB

**Comment by tadamski** [comment]
There also also quite a few references to the client inside basic integration testsuite - looking about it currently.

**Comment by fjuma** [comment]
Closing this one since it's been superseded by https://github.com/wildfly-security-incubator/wildfly/pull/44.

**Pull request closed without merging**
