### PR TITLE
[WFLY-8255] EJB authentication tests into elytron tests

### PR DESCRIPTION
**Pull request by thaarok**
Elytron EJB authentication tests removed (reverted) from basic and added into `testsuite/elytron` instead, where they should (by discussion with @kwart) be.

https://issues.jboss.org/browse/WFLY-8255

### CODE REVIEW

**Comment by darranl** [comment]
I am getting a test failure form this PR - once we have the component upgrades in ladybird may need to revisit this one tomorrow.

**Comment by thaarok** [comment]
Sorry, I have forgotten to commit @Ignores. Should be ok now.

**Comment by darranl** [comment]
Sorry @honza889 getting a merge conflict now, some parallel changes to the testsuite upstream are conflicting.

**Comment by thaarok** [comment]
Updated.

**Pull request merged**
