### PR TITLE
Fixing compilation issue due to changes in Elytron API.

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by darranl** [comment]
I think this fix is already in the branch.

**Comment by fjuma** [comment]
This fix doesn't seem to be in the branch, I ran into a compilation issue as well.

**Comment by darranl** [comment]
Sorry just found the changes are still in my local branch - I will send in a commit as this should really have a Jira ID.

**Comment by darranl** [comment]
Have pushed a fix for this.

**Pull request closed without merging**
