### PR TITLE
[WFLY-8532] Create test cases for Elytron Realm Mappers

### PR DESCRIPTION
**Pull request by olukas**
https://issues.jboss.org/browse/WFLY-8532
https://issues.jboss.org/browse/JBEAP-10201

### CODE REVIEW

**Review by kabir — APPROVED** [review]

**Comment by darranl** [comment]
This one will require a minor rebase as the testsuite is now at teststsuite/integration/elytron

**Review by darranl — CHANGES_REQUESTED** [review]
Just the minor change that the test needs to move to the new location.

**Comment by olukas** [comment]
Thanks for review. Tests were moved to testsuite/integration/elytron.

**Review by kwart — APPROVED** [review]
LGTM. The hints from @darranl are implemented.

**Pull request merged**
